### ISSUE TITLE
The screen is blurred due to multiple button clicks within a short time.

### ISSUE THREAD

**Issue by nenadsijan** [wire-elements/modal#431]
Hi PhiloNL
I am using LIvewire 3, TailwindCSS and your package Wire Elements Pro. 
Error:
An error occurs in the browser console if the button to open a modal class is clicked multiple times within a short period of time,
Error is` (Uncaught (in promise) Component not found: ZlYcx1wKYe0dQDAOEZ4j).`
In the next step when we want to close the modal `$dispatch('modal.close')`, the screen is blurred.

Here are the steps:

1.Multiple button clicks within a short period of time`<button type="button" wire:click="$dispatch('modal.open', {component: 'modals.edit-item', arguments: {id: 1}"></button> `
2. Modal is open, but we get error in the browser console ` __Uncaught (in promise) Component not found: ZlYcx1wKYe0dQDAOEZ4j__`
3. Clicking on the button to close the modal `wire:click="$dispatch('modal.close')"`
4. The screen is blurred

Thanks in advance
Nenad

**Comment by PhiloNL** [comment]
This should be fixed in `v4.0.14`, please make sure you use `wire:modal` instead, for example:

```html
<button wire:modal="modals.edit-item, @js(['id' => 1])">Open</button>
```

**Comment by nenadsijan** [comment]
Dear @PhiloNL
I upgraded Wire Elements Pro to version 4.0.14. But still I have problems:
1)I'm using now wire:modal for button click
`<button type="button" wire:modal="modals.edit-item, @js(['id' => 1])">Test</button>` 
2)But after click i'm getting this  error in browser console 
`livewire.js?id=5d8beb2e:1192 Alpine Expression Error: Invalid or unexpected tokenExpression: "@js(['id' => 1])", `
Thanks in advance
Best reagards
Nenad

**Comment by nenadsijan** [comment]
Dear @PhiloNL 
I upgraded to Wire Elements Pro to version 4.0.14
But I still get the same error when  button to open a modal class is quickly clicked multiple times 
Here are the steps:

1.  Multiple clicks on the button within a short period of time`<button type="button"  wire:modal="modals.edit-item, @js(['id' => 1])">aa</button>`
2.  Modal is open, but still there is a error in the browser console   `Uncaught (in promise) Component not found: e3HrnW0Ja54bVYzKjS8`
3.  Clicking on the button to close the modal wire:click="$dispatch('modal.close')"
4. The screen is blurred

BG
Nenad

**Comment by nenadsijan** [comment]
Dear @PhiloNL ,
Sorry for disstrubance, it was my fault. I forgout to execute `php artisan config:clear` after `composer update`
It works perfect now :)
Thanks a lot
Nenad
